2024-03-23 01:14:38,629 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"Time": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:15:04,908 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:15:04,909 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"Time": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:17:03,166 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:17:03,166 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"Time": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:17:31,755 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:17:31,755 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"Time": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:26:07,569 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:26:07,570 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"timestamp": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:26:29,170 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:26:29,170 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"timestamp": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:26:40,138 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:26:40,139 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"timestamp": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:27:33,035 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:27:33,035 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"timestamp": datetime.datetime.now("<YYYY-mm-ddTHH:MM:ss>"), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:29:14,078 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:29:14,078 ERROR: Exception on /api/Patrol_Data [POST] [in app.py: 1414]
Traceback (most recent call last):
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\sensor\arduino-data-logger\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "F:\sensor\arduino-data-logger\app\api\views.py", line 16, in add_sensor_reads
    Patrol_Data = {"timestamp": datetime.datetime.now(), "metadata": {"Area_ID": Area_ID}, "RFID": RFID,}
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2024-03-23 01:29:45,689 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
2024-03-23 01:30:54,669 INFO: Patrol_Data : {'RFID': 'E328BF0D', 'Area_ID': 1} [in views.py: 14]
